### ISSUE TITLE
Doesn't work with typescript?

### ISSUE THREAD

**Issue by shirshak55** [hCaptcha/react-hcaptcha#131]
```
yarn run v1.22.18
$ tsc && vite build
src/App.tsx:10:17 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

10                 <Cap
                   ~~~~
11                     sitekey="xyz"
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12                     // onVerify={(token: any, ekey: any) => handleVerificationSuccess(token, ekey)}
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13                 />
   ~~~~~~~~~~~~~~~~~~

src/App.tsx:10:18 - error TS2786: 'Cap' cannot be used as a JSX component.
  Its instance type 'HCaptcha' is not a valid JSX element.
    Type 'HCaptcha' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

10                 <Cap
                    ~~~


Found 2 errors in the same file, starting at: src/App.tsx:10

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

To reproduce create a new react typescript project using vite and add Hcaptcha component. I followed typescript advice but it doesn't work.

**Comment by MRmlik12** [comment]
I have the same problem

**Comment by jonasmarco** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/19959770/173198753-9d945a02-9d87-44e6-93ce-2efebea0cd74.png)

I have installed

> "@hcaptcha/react-hcaptcha": "^1.3.1",
> "@hcaptcha/types": "^1.0.2",

**Comment by zoryana94** [comment]
Hi,

We're working on the issue.
For now, I can suggest you [this workaround](https://getridbug.com/reactjs/jsx-element-class-does-not-support-attributes-because-it-does-not-have-a-props-property-ts2607/):

```
import HCaptcha from '@hcaptcha/react-hcaptcha';

interface HCaptchaFix extends React.Component {}

const HCaptchaNew = (HCaptcha as any) as {
  new(): HCaptchaFix;
};

// ...

const props = {
  sitekey: '10000000-ffff-ffff-ffff-000000000001',
  theme: 'light',
  onVerify: () => undefined
};

// ...

<HCaptchaNew {...props} />
```

Please let me know if that fixes the issue you have.
I'll let you know when we come up with the better solution.

Best Regards,
IM Dev Team

**Comment by zoryana94** [comment]
Hi @shirshak55 @MRmlik12 @jonasmarco,

Thank you for notifying us regarding the issue with Vite TS projects!
The issue should be fixed in our [latest release](https://github.com/hCaptcha/react-hcaptcha/releases/tag/1.4.1).

Please check it from your side and let us know if everything is working as expected.

Best Regards,
IM Dev Team

**Comment by shirshak55** [comment]
thanks

**Comment by builtbylane** [comment]
Hi @zoryana94 

Same issue here with latest react-hcaptcha while using `"jsx": "react-jsx"` in tsconfig

**Comment by zoryana94** [comment]
Hi @[builtbylane](https://github.com/builtbylane),

Thank you for notifying!
I've just checked and I cannot reproduce the issue you have.
What version of `vite` do you use? You may want to consider upgrading to the latest one. The Vite team has released the version 3 recently, and now it seems stable.
If it doesn't work for you, could you please describe the steps to reproduce it or send the link to the codesandbox?

Best Regards,
IMI Dev Team
