### ISSUE TITLE
props onLoad is not triggerd at second mount

### ISSUE THREAD

**Issue by cai-zhuo** [hCaptcha/react-hcaptcha#198]
Hello~
The Class Component seems only trigger `onLoad` once if iframe is already mounted,
My scenario is in Next.js App Router, I changed router to _/auth/signin_ from _/auth/signup_ , component `Hcaptcha` will unmount, but iframe is still existing, so in next time `Hcaptcha` mounted, it will not trigger `onLoad`.

thanks for help!

**Comment by zoryana94** [comment]
Hi @cai-zhuo ,

Thank you for reaching to us!
That's the expected behavior! The `onLoad` is triggered when the `hCaptcha` script is loaded.
You can find [more info here](https://github.com/hCaptcha/react-hcaptcha#references).

Right now, we don't have the prop that would be triggered when the new instance of hCaptcha is ready for use.
Please take a look if `captchaRef.current?.isReady()` could help you.
If you would like to solve some specific issue, please provide us with more details.

Best Regards,
hCaptcha Dev Team
